countries = ['USA', 'Canada', 'Spain', 'South Korea', 'Japan']
print(countries)
print(sorted(countries))
print(sorted(countries, reverse=True))
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
